@baseUrl = http://localhost:6400

### Health
GET {{baseUrl}}/api/v1/health

### List all Todos
GET {{baseUrl}}/api/v1/todos

### Get a specific todo
GET {{baseUrl}}/api/v1/todos/1

### Create a Todo
POST {{baseUrl}}/api/v1/todos
Content-Type: application/json

{
    "title": "An Example Todo",
    "description": "This is an example Todo"
}

### Update a Todo
PUT {{baseUrl}}/api/v1/todos/1
Content-Type: application/json

{
    "title": "updated title",
}

### Delete a todo
DELETE {{baseUrl}}/api/v1/todos/1
